- name: Testing
  hosts: localhost
  vars:
    env: testenv
    manager: "Bob Thomson"
    new_manager: "{{ manager if env == 'Teddy' else manager | replace('Bob', 'Bill') }}"
  tasks:
    - name: Get manager
      ansible.builtin.debug:
        msg: "{{ new_manager }}"

    - name: Get facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"
