- name: Testing
  hosts: localhost
  vars:
    env: nysiftest
    manager: "CN=Dominic Giunta,OU=User Accounts,OU=NYC ITS,OU=District Office,DC=nysif,DC=com"
    new_manager: "{{ manager if env == 'nysif' else manager | replace('DC=nysif', 'DC=nysiftest') }}"
  tasks:
    - name: Replace if env is nysiftest else leave it
      ansible.builtin.debug:
        msg: "{{ new_manager }}"

    - name: Get facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"
